apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base
commonLabels:
  environment: latest
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: conversion-guide-
nameSuffix: -latest
# Facilitate kustomization name updating
#
configurations:
  - kustomizeconfig.yaml
commonAnnotations:
  version: 1.3.1-0cecd0ae--2024-09-20.1726844879 # {"$imagepolicy": "conversion-guide:conversion-guide-image-policy-latest:tag"}
images:
  - name: "conversion-guide"
    newName: "registry.ltc.bcit.ca/web-apps/conversion-guide"
    newTag: "1.3.1-0cecd0ae--2024-09-20.1726844879" # {"$imagepolicy": "conversion-guide:conversion-guide-image-policy-latest:tag"}
patches:
  # Patches ingress with "latest--"
  - target:
      kind: Ingress
    path: ingress-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-latest/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-latest
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
