# You can override the included template(s) by including variable overrides
# SAST customization: https://docs.gitlab.com/ee/user/application_security/sast/#customizing-the-sast-settings
# Secret Detection customization: https://docs.gitlab.com/ee/user/application_security/secret_detection/#customizing-settings
# Dependency Scanning customization: https://docs.gitlab.com/ee/user/application_security/dependency_scanning/#customizing-the-dependency-scanning-settings
# Container Scanning customization: https://docs.gitlab.com/ee/user/application_security/container_scanning/#customizing-the-container-scanning-settings
# Note that environment variables can be set in several places
# See https://docs.gitlab.com/ee/ci/variables/#cicd-variable-precedence
stages:
- get info
- publish
- cleanup
- test
project init:
  stage: get info
  extends:
  - ".project_init"
get info:
  stage: get info
  extends:
  - ".get_info"
build image:
  stage: publish
  extends:
  - ".build_image"
  - ".build_image_rules"
deploy review:
  stage: publish
  variables:
    TARGET_ENV: dev
  extends:
  - ".deploy_review"
  - ".deploy_review_rules"
deploy to staging:
  stage: publish
  variables:
    TARGET_ENV: staging
  extends:
  - ".deploy"
  - ".deploy_staging_rules"
  environment:
    name: staging
    url: https://$STAGING_HOST/$CI_PROJECT_NAME
  tags:
  - staging
deploy to production:
  stage: publish
  variables:
    TARGET_ENV: production
  extends:
  - ".deploy"
  - ".deploy_prod_rules"
  environment:
    name: production
    url: https://${PROD_HOST}/${CI_PROJECT_NAME}
  tags:
  - production
stop review:
  stage: cleanup
  extends:
  - ".undeploy_review"
  - ".undeploy_review_rules"
variables:
  CLUSTER_NAME: dev-cp
  DEPLOY_PKG_PROJECT_ID: '404'
  PIPELINE_DEBUG: 'true'
include:
- project: deployments/ci-config
  file:
  - project-init.yml
  - get-info.yml
  - build.yml
  - deploy.yml
  - ".deploy-hydrate.yml"
  - ".vault.yml"
  - ".rules.yml"
- template: Jobs/SAST.gitlab-ci.yml
- template: Jobs/Secret-Detection.gitlab-ci.yml
- template: Security/License-Scanning.gitlab-ci.yml
- template: Security/Container-Scanning.gitlab-ci.yml
default:
  tags:
  - "${CLUSTER_NAME}"
workflow:
  rules:
  - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
    when: never
  - if: "$CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS"
    when: never
  - if: $CI_PIPELINE_SOURCE == "merge_request_event" || $CI_COMMIT_BRANCH || $CI_COMMIT_TAG
sast:
  stage: test
