version: "3"

services:
  app:
    image: conversionguide
    build:
      context: .
      target: builder
    command: npm run watch
    environment:
      - DEBUG=True
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3000:3000"
      - "3001:3001"
