version: "3"

services:
  app:
    image: conversionguide
    # image: node:12
    build:
      context: .
      target: development
    command: npm run quickly
    environment:
      - DEBUG=True
    working_dir: /app
    volumes:
      - .:/app
    ports:
      - "3001:3001"
      - "3002:3002"
      - "8080:8080"
