services:
  app:
    image: conversion-guide
    build:
      context: .
      target: release
    # command: npm run watch
    environment:
      - DEBUG=True
    working_dir: /app
    # volumes:
    #   - .:/app
    ports:
      - "8080:8080"
