apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: conversion-guide
resources:
  - ../../base
# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: conversion-guide-
nameSuffix: -stable
# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml
commonLabels:
  environment: stable
commonAnnotations:
  version: 1.2.10 # {"$imagepolicy": "conversion-guide:conversion-guide-image-policy-stable:tag"}
images:
  - name: "conversion-guide"
    newName: "registry.ltc.bcit.ca/web-apps/conversion-guide"
    newTag: "1.2.10" # {"$imagepolicy": "conversion-guide:conversion-guide-image-policy-stable:tag"}
patches:
  # Patches deployment with secrets
  - target:
      kind: Deployment
    path: deployment-patch.yaml
  # Incorporate vault-secrets
  #
  # adds `-latest` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-stable/vault-auth-patch.yaml
components:
  # Include environment-specific secrets
  - ./vault-secrets-stable
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
configMapGenerator:
  # Updates elasticapm config
  - name: elasticapm-config
    literals:
      - ELASTIC_APM_SERVICE_NAME=conversion-guide-stable
    behavior: merge