apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: conversion-guide-

resources:
  - serviceaccount.yaml
  - ./nginx-unprivileged
  - ingress.yaml

commonLabels:
  app: conversion-guide
  app.kubernetes.io/name: conversion-guide


# Patch nginx base; simplify deployment name
#
patches:
  - target:
      kind: Deployment
    patch: |-
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: conversion-guide
      - op: replace
        path: /spec/template/spec/containers/0/name
        value: conversion-guide
      - op: add
        path: /spec/template/spec/serviceAccountName
        value: conversion-guide-serviceaccount
      - op: replace
        path: /metadata/name
        value: deployment

configMapGenerator:
  - name: config
    files:
      - nginx.conf
    behavior: replace